const SECTION = 'REGISTRATION_MANAGEMENT_';

const AC_INIT_FETCH = SECTION + 'AC_INIT_FETCH';
const AC_ERR_FETCH = SECTION + 'AC_ERR_FETCH';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';

export default { AC_INIT_FETCH, AC_ERR_FETCH, AC_END_FETCH };
