const SECTION = 'PERMISSIONS_AND_USERS_';

const AC_INIT_OPERATION = SECTION + 'AC_INIT_OPERATION';
const AC_END_OPERATION = SECTION + 'AC_END_OPERATION';
const AC_DELETE_GROUPS_OPTIONS = SECTION + 'AC_DELETE_GROUPS_OPTIONS';
const AC_END_FETCH_GROUP_DATA = SECTION + 'AC_END_FETCH_GROUP_DATA';
const AC_SET_GROUP_DATA = SECTION + 'AC_SET_GROUP_DATA';
const AC_END_FETCH_USER_PERMISSION_DATA = SECTION + 'AC_END_FETCH_USER_PERMISSION_DATA';
const AC_SET_USER_PERMISSION_DATA = SECTION + 'AC_SET_USER_PERMISSION_DATA';
const AC_SET_EXCLUDED_USERS = SECTION + 'AC_SET_EXCLUDED_USERS';

export default {
  AC_INIT_OPERATION,
  AC_END_OPERATION,
  AC_DELETE_GROUPS_OPTIONS,
  AC_END_FETCH_GROUP_DATA,
  AC_SET_GROUP_DATA,
  AC_END_FETCH_USER_PERMISSION_DATA,
  AC_SET_USER_PERMISSION_DATA,
  AC_SET_EXCLUDED_USERS
};
