const SECTION = 'GLOBAL_POPUPS_';

const AC_SHOW_MESSAGE = SECTION + 'AC_SHOW_MESSAGE';
const AC_SET_POPUP_OPEN = SECTION + 'AC_SET_POPUP_OPEN';

export default { AC_SHOW_MESSAGE, AC_SET_POPUP_OPEN };
