const SECTION = 'SET_PASSWORD_';

const AC_INIT_SET_PASSWORD = SECTION + 'AC_INIT_SET_PASSWORD';
const AC_END_SET_PASSWORD = SECTION + 'AC_END_SET_PASSWORD';

export default { AC_INIT_SET_PASSWORD, AC_END_SET_PASSWORD };
