const SECTION = 'CREATE_NEW_PANEL_SETS_';

const AC_INIT_CREATE = SECTION + 'AC_INIT_CREATE';
const AC_END_CREATE = SECTION + 'AC_END_CREATE';
const AC_ERR_CREATE = SECTION + 'AC_ERR_CREATE';
const AC_INIT_SEND = SECTION + 'AC_INIT_SEND';
const AC_END_SEND = SECTION + 'AC_INIT_SEND';
const AC_UPDATE_FORM_VALUES = SECTION + 'AC_UPDATE_FORM_VALUES';
const AC_RESET_FORM_VALUE = SECTION + 'AC_RESET_FORM_VALUE';

export default { AC_RESET_FORM_VALUE, AC_INIT_CREATE, AC_END_CREATE, AC_ERR_CREATE, AC_INIT_SEND, AC_END_SEND, AC_UPDATE_FORM_VALUES };
