const SECTION = 'CONFIGURATION_';

const AC_INIT_FETCH = SECTION + 'AC_INIT_FETCH';
const AC_ERR_FETCH = SECTION + 'AC_ERR_FETCH';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';
const AC_LOAD_CONFIG_DATA = SECTION + 'AC_LOAD_CONFIG_DATA';
const AC_UPDATE_CONFIG_DATA = SECTION + 'AC_UPDATE_CONFIG_DATA';
const AC_SET_VALIDATION_PUNDRUG = SECTION + 'AC_SET_VALIDATION_PUNDRUG';
const AC_SET_VALIDATION_GENOM_DICT = SECTION + 'AC_SET_VALIDATION_GENOM_DICT';
const AC_SET_RESET_VALIDATIONS = SECTION + 'AC_SET_RESET_VALIDATIONS';

export default { AC_SET_RESET_VALIDATIONS, AC_INIT_FETCH, AC_ERR_FETCH, AC_END_FETCH, AC_UPDATE_CONFIG_DATA, AC_LOAD_CONFIG_DATA, AC_SET_VALIDATION_PUNDRUG, AC_SET_VALIDATION_GENOM_DICT };
