const SECTION = 'CONFIGURATION_';

const AC_INIT_FETCH = SECTION + 'AC_INIT_FETCH';
const AC_ERR_FETCH = SECTION + 'AC_ERR_FETCH';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';
const AC_UPDATE_CONFIG_DATA = SECTION + 'AC_UPDATE_CONFIG_DATA';
//const AC_VALIDATION_DIR_GEN_URL = SECTION + 'AC_VALIDATION_DIR_GEN_URL';

export default { AC_INIT_FETCH, AC_ERR_FETCH, AC_END_FETCH, AC_UPDATE_CONFIG_DATA };
