const SECTION = 'PASSWORD_REQUEST_';

const AC_INIT_PASSWORD_REQUEST = SECTION + 'AC_INIT_PASSWORD_REQUEST';
const AC_END_PASSWORD_REQUEST = SECTION + 'AC_END_PASSWORD_REQUEST';

export default { AC_INIT_PASSWORD_REQUEST, AC_END_PASSWORD_REQUEST };
