const SECTION = 'PROJECT_PROFILE_';

const AC_INIT_OPERATION = SECTION + 'AC_INIT_OPERATION';
const AC_ERR_OPERATION = SECTION + 'AC_ERR_OPERATION';
const AC_END_OPERATION = SECTION + 'AC_END_OPERATION';

const AC_END_FETCH_DATA = SECTION + 'AC_END_FETCH_DATA';

const AC_RESET_REDUX_PROJECT = SECTION + 'AC_RESET_REDUX_PROJECT';

const AC_SET_MODE = SECTION + 'AC_SET_MODE';

export default { AC_INIT_OPERATION, AC_ERR_OPERATION, AC_END_OPERATION, AC_END_FETCH_DATA, AC_RESET_REDUX_PROJECT, AC_SET_MODE };
