const SECTION = 'REGISTRATION_REQUEST_';

const AC_INIT_OPERATION = SECTION + 'AC_INIT_OPERATION';
const AC_END_OPERATION = SECTION + 'AC_END_OPERATION';
const AC_ERR_OPERATION = SECTION + 'AC_ERR_OPERATION';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';

export default {
  AC_INIT_OPERATION,
  AC_END_OPERATION,
  AC_ERR_OPERATION,
  AC_END_FETCH
};
