const SECTION = 'GENOMIC_REF_POPUP_';

const AC_INIT_FETCH = SECTION + 'AC_INIT_FETCH';
const AC_ERR_FETCH = SECTION + 'AC_ERR_FETCH';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';
const AC_INIT_FETCH_TABLE = SECTION + 'AC_INIT_FETCH_TABLE';
const AC_ERR_FETCH_TABLE = SECTION + 'AC_ERR_FETCH_TABLE';
const AC_END_FETCH_TABLE = SECTION + 'AC_END_FETCH_TABLE';
const AC_LOAD_SPIECES_DATA = SECTION + 'AC_LOAD_SPIECES_DATA';
const AC_LOAD_GENOMIC_REFERENCE_DATA = SECTION + 'AC_LOAD_GENOMIC_REFERENCE_DATA';
const AC_UPDATE_GENOMIC_REFERENCE_DATA = SECTION + 'AC_UPDATE_GENOMIC_REFERENCE_DATA';
const AC_RESET_GENOMIC_REFERENCE = SECTION + 'AC_RESET_GENOMIC_REFERENCE';

const AC_LOAD_ENSEMBL_RELEASE_DATA = SECTION + 'AC_LOAD_ENSEMBL_RELEASE_DATA';
const AC_LOAD_ASSEMBLY_DATA = SECTION + 'AC_LOAD_ASSEMBLY_DATA';

const AC_OPEN_SPECIES_TABLE_POPUP = SECTION + 'AC_OPEN_SPECIES_TABLE_POPUP';
const AC_OPEN_ASSEMBLY_TABLE_POPUP = SECTION + 'AC_OPEN_ASSEMBLY_TABLE_POPUP';

export default {
  AC_OPEN_ASSEMBLY_TABLE_POPUP,
  AC_OPEN_SPECIES_TABLE_POPUP,
  AC_LOAD_ENSEMBL_RELEASE_DATA,
  AC_LOAD_GENOMIC_REFERENCE_DATA,
  AC_INIT_FETCH,
  AC_ERR_FETCH,
  AC_END_FETCH,
  AC_INIT_FETCH_TABLE,
  AC_ERR_FETCH_TABLE,
  AC_END_FETCH_TABLE,
  AC_LOAD_SPIECES_DATA,
  AC_LOAD_ASSEMBLY_DATA,
  AC_UPDATE_GENOMIC_REFERENCE_DATA,
  AC_RESET_GENOMIC_REFERENCE
};
