const SECTION = 'LOGIN_';

const AC_INIT_LOGIN = SECTION + 'AC_INIT_LOGIN';
const AC_END_LOGIN = SECTION + 'AC_END_LOGIN';
const AC_ERR_LOGIN = SECTION + 'AC_ERR_LOGIN';
const SET_USER_DATA = SECTION + 'SET_USER_DATA';
const SET_TOKEN = SECTION + 'SET_TOKEN';
const LOGOUT = SECTION + 'LOGOUT';

export default { AC_INIT_LOGIN, AC_END_LOGIN, AC_ERR_LOGIN, SET_USER_DATA, SET_TOKEN, LOGOUT };
