const SECTION = 'LOGIN_';

const AC_INIT_OPERATION = SECTION + 'AC_INIT_OPERATION';
const AC_END_OPERATION = SECTION + 'AC_END_OPERATION';
const AC_END_LOGIN = SECTION + 'AC_END_LOGIN';
const AC_ERR_LOGIN = SECTION + 'AC_ERR_LOGIN';
const SET_USER_DATA = SECTION + 'SET_USER_DATA';
const SET_TOKEN = SECTION + 'SET_TOKEN';
const LOGOUT = SECTION + 'LOGOUT';
const SET_USER_PERMISSIONS = SECTION + 'SET_USER_PERMISSIONS';

// Config Data
const AC_END_FETCH_CONFIG_DATA = SECTION + 'AC_END_FETCH_CONFIG_DATA';
const AC_ERR_FETCH_CONFIG_DATA = SECTION + 'AC_ERR_FETCH_CONFIG_DATA';
const AC_UPDATE_CONFIG_DATA = SECTION + 'AC_UPDATE_CONFIG_DATA';

export default {
  AC_INIT_OPERATION,
  AC_END_OPERATION,
  AC_END_LOGIN,
  AC_ERR_LOGIN,
  SET_USER_DATA,
  SET_TOKEN,
  LOGOUT,
  AC_END_FETCH_CONFIG_DATA,
  AC_ERR_FETCH_CONFIG_DATA,
  AC_UPDATE_CONFIG_DATA,
  SET_USER_PERMISSIONS
};
