const SECTION = 'INDIVIDUAL_DETAILS_';

const AC_INIT_OPERATION = SECTION + 'AC_INIT_OPERATION';
const AC_END_OPERATION = SECTION + 'AC_END_OPERATION';
const AC_END_FETCH_DATA = SECTION + 'AC_END_FETCH_DATA';
const AC_RESET_REDUX_INDIVIDUAL = SECTION + 'AC_RESET_REDUX_INDIVIDUAL';
const AC_ADD_HPO = SECTION + 'AC_ADD_HPO';
const AC_DELETE_HPO = SECTION + 'AC_DELETE_HPO';
const AC_ADD_ICD10 = SECTION + 'AC_ADD_ICD10';
const AC_DELETE_ICD10 = SECTION + 'AC_DELETE_ICD10';
const AC_UPDATE_HPO = SECTION + 'AC_UPDATE_HPO';
const AC_UPDATE_ICD10 = SECTION + 'AC_UPDATE_ICD10';
const AC_SET_PERMISSIONS_DATA = SECTION + 'AC_SET_PERMISSIONS_DATA';
const AC_INIT_FETCH_PERMISSIONS_DATA = SECTION + 'AC_INIT_FETCH_PERMISSIONS_DATA';
const AC_END_FETCH_PERMISSIONS_DATA = SECTION + 'AC_END_FETCH_PERMISSIONS_DATA';
const AC_SET_EXCLUDED_USERS = SECTION + 'AC_SET_EXCLUDED_USERS';
const AC_REMOVE_EXCLUDED_USER = SECTION + 'AC_REMOVE_EXCLUDED_USER';

export default {
  AC_INIT_OPERATION,
  AC_END_OPERATION,
  AC_END_FETCH_DATA,
  AC_RESET_REDUX_INDIVIDUAL,
  AC_ADD_HPO,
  AC_DELETE_HPO,
  AC_ADD_ICD10,
  AC_DELETE_ICD10,
  AC_UPDATE_HPO,
  AC_UPDATE_ICD10,
  AC_SET_PERMISSIONS_DATA,
  AC_INIT_FETCH_PERMISSIONS_DATA,
  AC_END_FETCH_PERMISSIONS_DATA,
  AC_SET_EXCLUDED_USERS,
  AC_REMOVE_EXCLUDED_USER
};
