const SECTION = 'CREATE_NEW_USER_';

const AC_INIT_CREATE = SECTION + 'AC_INIT_CREATE';
const AC_END_CREATE = SECTION + 'AC_END_CREATE';
const AC_ERR_CREATE = SECTION + 'AC_ERR_CREATE';

const AC_RESET_POPUPS = SECTION + 'AC_RESET_POPUPS';

export default { AC_INIT_CREATE, AC_END_CREATE, AC_ERR_CREATE, AC_RESET_POPUPS };
