const SECTION = 'PANEL_SET_PROFILE_';

const AC_INIT_FETCH = SECTION + 'AC_INIT_FETCH';
const AC_ERR_FETCH = SECTION + 'AC_ERR_FETCH';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';
const AC_LOAD_PANEL_SET_DATA = SECTION + 'AC_LOAD_PANEL_SET_DATA';
const AC_UPDATE_PANEL_SET_DATA = SECTION + 'AC_UPDATE_PANEL_SET_DATA';

export default { AC_UPDATE_PANEL_SET_DATA, AC_INIT_FETCH, AC_ERR_FETCH, AC_END_FETCH, AC_LOAD_PANEL_SET_DATA };
