const SECTION = 'TAB_PANEL_';

const AC_INIT_FETCH = SECTION + 'AC_INIT_FETCH';
const AC_ERR_FETCH = SECTION + 'AC_ERR_FETCH';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';
const AC_LOAD_PANEL_DATA = SECTION + 'AC_LOAD_PANEL_DATA';
const AC_UPDATE_PANEL_DATA = SECTION + 'AC_UPDATE_PANEL_DATA';
const AC_NEW_ASCENDANT = SECTION + 'AC_NEW_ASCENDANT';
const AC_NEW_DESCENDANT = SECTION + 'AC_NEW_DESCENDANT';
const AC_DELETE_ASCENDANT = SECTION + 'AC_DELETE_ASCENDANT';
const AC_DELETE_DESCENDANT = SECTION + 'AC_DELETE_DESCENDANT';
const AC_NEW_REGION = SECTION + 'AC_NEW_REGION';
const AC_NEW_VARIANT = SECTION + 'AC_NEW_VARIANT';
const AC_DELETE_REGION = SECTION + 'AC_DELETE_REGION';
const AC_DELETE_VARIANT = SECTION + 'AC_DELETE_VARIANT';
const AC_INIT_CREATE = SECTION + 'AC_INIT_CREATE';
const AC_END_CREATE = SECTION + 'AC_END_CREATE';
const AC_ERR_CREATE = SECTION + 'AC_ERR_CREATE';
const AC_RESET_GENONIC_REFERENCE = SECTION + 'AC_RESET_GENONIC_REFERENCE';
const AC_PANELSET_ID = SECTION + 'AC_PANELSET_ID';
const AC_ASSEMBLY_ID = SECTION + 'AC_ASSEMBLY_ID';
const AC_DELETE_GENE = SECTION + 'AC_DELETE_GENE';
const AC_ADD_GENE = SECTION + 'AC_ADD_GENE';
const AC_DELETE_TRANSCRIPT = SECTION + 'AC_DELETE_TRANSCRIPT';
const AC_ADD_TRANSCRIPT = SECTION + 'AC_ADD_TRANSCRIPT';
const AC_DELETE_HPO = SECTION + 'AC_DELETE_HPO';
const AC_ADD_HPO = SECTION + 'AC_ADD_HPO';
const AC_ADD_ICD10 = SECTION + 'AC_ADD_ICD10';
const AC_DELETE_ICD10 = SECTION + 'AC_DELETE_ICD10';

export default {
  AC_RESET_GENONIC_REFERENCE,
  AC_INIT_CREATE,
  AC_END_CREATE,
  AC_ERR_CREATE,
  AC_LOAD_PANEL_DATA,
  AC_UPDATE_PANEL_DATA,
  AC_NEW_ASCENDANT,
  AC_NEW_DESCENDANT,
  AC_NEW_REGION,
  AC_NEW_VARIANT,
  AC_INIT_FETCH,
  AC_ERR_FETCH,
  AC_END_FETCH,
  AC_DELETE_ASCENDANT,
  AC_DELETE_DESCENDANT,
  AC_DELETE_REGION,
  AC_DELETE_VARIANT,
  AC_PANELSET_ID,
  AC_ASSEMBLY_ID,
  AC_DELETE_GENE,
  AC_ADD_GENE,
  AC_DELETE_TRANSCRIPT,
  AC_ADD_TRANSCRIPT,
  AC_DELETE_HPO,
  AC_ADD_HPO,
  AC_ADD_ICD10,
  AC_DELETE_ICD10
};
