const SECTION = 'DRUGS_MANAGEMENT_';

const AC_INIT_AVAILABLE = SECTION +'AC_INIT_AVAILABLE';
const AC_ERR_AVAILABLE = SECTION +'AC_ERR_AVAILABLE';
const AC_END_AVAILABLE = SECTION +'AC_END_AVAILABLE';

export default { AC_END_AVAILABLE, AC_INIT_AVAILABLE, AC_ERR_AVAILABLE };
