const SECTION = 'DRUGS_MANAGEMENT_';

const AC_INIT_FETCH = SECTION + 'AC_INIT_FETCH';
const AC_ERR_FETCH = SECTION + 'AC_ERR_FETCH';
const AC_END_FETCH = SECTION + 'AC_END_FETCH';
const AC_INIT_AVAILABLE = SECTION +'AC_INIT_AVAILABLE';
const AC_ERR_AVAILABLE = SECTION +'AC_ERR_AVAILABLE';
const AC_END_AVAILABLE = SECTION +'AC_END_AVAILABLE';

export default { AC_INIT_FETCH, AC_ERR_FETCH, AC_END_FETCH, AC_END_AVAILABLE, AC_INIT_AVAILABLE, AC_ERR_AVAILABLE };
