const SECTION = 'DRUG_PROFILE_';

const AC_INIT_OPERATION = SECTION + 'AC_INIT_OPERATION';
const AC_ERR_OPERATION = SECTION + 'AC_ERR_OPERATION';

const AC_END_FETCH_DATA = SECTION + 'AC_END_FETCH_DATA';
const AC_END_UPDATE_DRUG = SECTION + 'AC_END_UPDATE_DRUG';

const AC_SET_DATA = SECTION + 'AC_SET_DATA';

export default { AC_INIT_OPERATION, AC_ERR_OPERATION, AC_END_FETCH_DATA, AC_END_UPDATE_DRUG, AC_SET_DATA };
