const SECTION = 'USER_PROFILE_';

const AC_INIT_OPERATION = SECTION + 'AC_INIT_OPERATION';
const AC_ERR_OPERATION = SECTION + 'AC_ERR_OPERATION';
const AC_END_OPERATION = SECTION + 'AC_END_OPERATION';

const AC_END_FETCH_DATA = SECTION + 'AC_END_FETCH_DATA';
const AC_END_UPDATE_USER = SECTION + 'AC_END_UPDATE_USER';

const AC_SET_DATA = SECTION + 'AC_SET_DATA';
const AC_SET_USER_SELECTION_POPUP_OPEN = SECTION + 'AC_SET_USER_SELECTION_POPUP_OPEN';

export default { AC_INIT_OPERATION, AC_ERR_OPERATION, AC_END_OPERATION, AC_END_FETCH_DATA, AC_END_UPDATE_USER, AC_SET_DATA, AC_SET_USER_SELECTION_POPUP_OPEN };
