const PATH_LOGIN = '/login';
const PATH_HOME = '/home';
const PATH_FORGOT_PASSWORD = '/forgot-password';
const PATH_SET_PASSWORD = '/new-password';
const PATH_USERS_MANAGEMENT = '/users-management';
const PATH_DRUGS_MANAGEMENT = '/drugs-management';
const PATH_REGISTRATION_MANAGEMENT = '/registration-management';
const PATH_USER_PROFILE = '/profile';
const PATH_DRUG_PROFILE = '/drug';
const PATH_ADMIN_CREATE_USER = '/create-user';
const PATH_ADMIN_REVIEW_REQUEST = '/review-request';
const PATH_ADMIN_CONFIGURATION = '/app-configuration';
const PATH_MAINTENANCE = '/maintenance';
const PATH_PANEL_SETS_MANAGEMENT = '/panel-collections-management';
const PATH_CREATE_PANEL_SET = '/create-panel-set';
const PATH_PANEL_SET_PROFILE = '/panel-set-profile';
const PATH_TAB_PANEL_DIAGNOSTIC = '/tab-panel-diagnostic';
const PATH_PROJECTS_MANAGEMENT = '/projects-management';
const PATH_PROJECT_PROFILE = '/project';
const PATH_PERMISSIONS_AND_USERS = '/permissions';
const PATH_INDIVIDUALS_MANAGEMENT = '/individuals-management';
const PATH_INDIVIDUALS_DETAILS = '/individual';


export default {
  PATH_LOGIN,
  PATH_HOME,
  PATH_FORGOT_PASSWORD,
  PATH_SET_PASSWORD,
  PATH_USERS_MANAGEMENT,
  PATH_DRUGS_MANAGEMENT,
  PATH_REGISTRATION_MANAGEMENT,
  PATH_USER_PROFILE,
  PATH_ADMIN_CREATE_USER,
  PATH_ADMIN_REVIEW_REQUEST,
  PATH_DRUG_PROFILE,
  PATH_ADMIN_CONFIGURATION,
  PATH_MAINTENANCE,
  PATH_PANEL_SETS_MANAGEMENT,
  PATH_CREATE_PANEL_SET,
  PATH_PANEL_SET_PROFILE,
  PATH_TAB_PANEL_DIAGNOSTIC,
  PATH_PROJECTS_MANAGEMENT,
  PATH_PROJECT_PROFILE,
  PATH_PERMISSIONS_AND_USERS,
  PATH_INDIVIDUALS_MANAGEMENT,
  PATH_INDIVIDUALS_DETAILS
};
